namespace app\adminapi\controller;


use app\common\service\<?php echo $moduleName?>Service;
use app\adminapi\controller\Backend;

/**
 * <?php echo $controllerName?>管理-控制器
 * @author <?php echo $author?>

 * @since: <?php echo $since?>

 * Class <?php echo $controllerName?>

 * @package app\adminapi\controller
 */
class <?php echo $controllerName?> extends Backend
{
    /**
     * 初始化方法
     * @author <?php echo $author?>

     * @since: <?php echo $since?>

     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new <?php echo $moduleName?>Service();
    }

<?php if ($columnList) {?>
<?php foreach ($columnList as $val) { ?>
    <?php if (isset($val['columnSwitch']) && $val['columnSwitch']) {?>
    <?php if ($val['columnName'] != "status") {?>

	/**
	 * 设置<?php echo $val['columnComment']?>

	 * @return mixed
	 * @since <?php echo $since?>

	 * @author <?php echo $author?>

	 */
	public function <?php echo $val['columnSwitchName']?>()
	{
		if (IS_POST) {
			$result = $this->service-><?php echo $val['columnSwitchName']?>();
			return $result;
		}
	}
    <?php } ?>
	<?php } ?>
<?php } ?>
<?php } ?>

}
