<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


use app\common\service\AdminUserRoleService;

/**
 * 用户-模型
 * @author 牧羊人
 * @since 2020/11/14
 * Class User
 * @package app\common\model
 */
class AdminUser extends BaseModel
{
    // 设置数据表名称
    protected $name = "admin_user";

    /**
     * 获取数据信息
     * @param int $id 用户ID
     * @return 数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 牧羊人
     * @since 2020/11/14
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 头像
            if ($info['avatar']) {
                $info['avatar'] = get_image_url($info['avatar']);
            }

            // 性别
            if ($info['gender']) {
                $info['gender_name'] = config('admin.gender_list')[$info['gender']];
            }
            // 出生日期
            if ($info['birthday']) {
                $info['birthday'] = datetime($info['birthday']);
            }

            // 城市
            $city = [];
            $city[] = !empty($info['province_code']) ? strval($info['province_code']) : "";
            $city[] = !empty($info['city_code']) ? strval($info['city_code']) : "";
            $city[] = !empty($info['district_code']) ? strval($info['district_code']) : "";
            $info['city'] = $city;

            // 职级
            if ($info['level_id']) {
                $levelMod = new Level();
                $levelInfo = $levelMod->getInfo($info['level_id']);
                $info['level_name'] = $levelInfo['name'];
            }

//            // 岗位
//            if ($info['position_id']) {
//                $positionModel = new Position();
//                $positionInfo = $positionModel->getInfo($info['position_id']);
////                $info['position_name'] = $positionInfo['name'];
//            }

            // 获取用户角色列表
            $userRoleService = new AdminUserRoleService();
            $roleList = $userRoleService->getUserRoleList($id);
            $info['roles'] = $roleList;

        }
        return $info;
    }

}
