<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;

/**
 * 广告位-模型
 * @author 牧羊人
 * @since 2020/11/15
 * Class AdSort
 * @package app\common\model
 */
class AdSort extends BaseModel
{
    // 设置数据表名
    protected $name = "ad_sort";

    /**
     * 获取记录信息
     * @param int $id 广告位ID
     * @return 数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 牧羊人
     * @since 2020/11/15
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 获取栏目名称
            if ($info['cate_id']) {
                $itemCateModel = new ItemCate();
                $itemCateName = $itemCateModel->getCateName($info['cate_id'], ">>");
                $info['item_cate_name'] = $itemCateName;
            }
        }
        return $info;
    }

}
