<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 策略记录-模型
 * @author 测试
 * @since: 2023/09/26
 * Class ProductOrder
 * @package app\adminapi\model
 */
class ProductOrder extends BaseModel
{
    // 设置数据表名
    public $name = "product_order";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2023/09/26
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $info['product'] = Product::where('id',$info['product_id'])->find();
            $info['product_name'] =  $info['product']['name'];
            $info['user'] = Member::where('id',$info['user_id'])->value('username');
            $info['platform'] =$info['platform_id']==2?'欧意':'币安';
            $info['loss'] =$info['now_money']-$info['invest'];
            $info['loss_rate'] =$info['loss'] /$info['invest'] ;
            $info['day'] =(int)((time()-strtotime($info['create_time']))/(24*60*60)) ;

        }
        return $info;
    }


}
