<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 累计收益-模型
 * @author 测试
 * @since: 2023/09/27
 * Class ProductLog
 * @package app\adminapi\model
 */
class ProductLog extends BaseModel
{
    // 设置数据表名
    public $name = "product_log";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2023/09/27
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
              $info['creatr'] = date('Y-m-d',strtotime( $info['create_time']));
            $info['product'] = Product::where('id',$info['product_id'])->find();
            $info['product_name'] =  $info['product']['name'];
            $info['user'] = Member::where('id',$info['user_id'])->value('username');
        }
        return $info;
    }


}
