<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 钱包奖励-模型
 * @author 测试
 * @since: 2022/01/23
 * Class QuantWallet
 * @package app\adminapi\model
 */
class QuantWallet extends BaseModel
{
    // 设置数据表名
    public $name = "quant_wallet";


    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2022/01/23
     */
    public function getInfo($id)
    {
        $type = [1=>'充值','2'=>"提款", 4=>'团队奖励', 5=>'盈利服务费',0=>'',6=>'直推奖励',7=>'转账'];
        $payment_id = [1=>'支出', 2=>'收入',0=>''];
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $info['num'] =floatval($info['num']);
            $info['num'] =sprintf("%.4f",($info['num']));
            $info['last_num'] = getBcRound($info['last_num'],4);
            $user = new Member();
            $member = $user->where('id',$info['user_id'])->find();
            if($member){
                $info['user_name']=$member['username'];
            }else{
                $info['user_name']='';
            }
            if(isset($payment_id[$info['payment_id']])){
                $info['type_name']=$payment_id[$info['payment_id']];
            }
            if(isset($type[$info['type_id']])){
                $info['type_name']=$type[$info['type_id']];
            }
        }
        return $info;
    }


}
