<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 转账记录-模型
 * @author 测试
 * @since: 2022/11/17
 * Class QuantMove
 * @package app\adminapi\model
 */
class QuantMove extends BaseModel
{
    // 设置数据表名
    public $name = "quant_move";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2022/11/17
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $info['amount']=abs($info['amount']);
            $user = new Member();
            $member = $user->where('id',$info['user_id_from'])->find();
            $info['user_from']=$member['username'];
            $member = $user->where('id',$info['user_id_to'])->find();
            $info['user_to']=$member['username'];
        }
        return $info;
    }


}
