<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 点卡流水-模型
 * @author 测试
 * @since: 2022/03/18
 * Class QuantPoint
 * @package app\adminapi\model
 */
class QuantPoint extends BaseModel
{
    // 设置数据表名
    public $name = "quant_point";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2022/03/18
     */
    public function getInfo($id)
    {
        $type = [1=>'充值', 3=>'开通AI', 2=>'手续费',0=>''];
        $payment_id = [1=>'支出', 2=>'收入',0=>''];
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $info['num'] =floatval($info['num']);
            $info['num'] = sprintf("%.2f",$info['num']);
            $user = new Member();
            $member = $user->where('id',$info['user_id'])->find();
            if($member){
                $info['user_name']=$member['username'];
            }else{
                $info['user_name']='';
            }
            $info['type_name']=$type[$info['type_id']];
            $info['payment_name']=$payment_id[$info['payment_id']];
        }
        return $info;
    }


}
