<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;


/**
 * 充值-模型
 * @author 测试
 * @since: 2022/01/23
 * Class QuantTransfer
 * @package app\adminapi\model
 */
class QuantTransfer extends BaseModel
{
    // 设置数据表名
    public $name = "quant_transfer";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 测试
     * @since: 2022/01/23
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $info['value']=   getBcRound($info['value'],4);
            $user = new Member();
            $member = $user->where('id',$info['user_id'])->find();
            if($member){
                $info['user_name']=$member['username'];
            }else{
                $info['user_name']='';
            }
        }
        return $info;
    }


}
