<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\model;

/**
 * 字典-模型
 * @author 牧羊人
 * @since 2020/11/15
 * Class DictType
 * @package app\common\model
 */
class SingleLoopSetup extends BaseModel
{
    // 设置数据表名
    protected $name = "single_loop_setup";


    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            $user = new Member();
            $member = $user->where('id',$info['user_id'])->find();
            if($member){
                $info['user_name']=$member['username'];
            }else{
                $info['user_name']='';
            }
        }
        return $info;
    }
    public function getQbTokenAttr($value)
    {
        return (float)$value;
    }
    public function getMinTokenAttr($value)
    {
        return (float)$value;
    }
}


