<?php namespace app\adminapi\controller;


use app\common\service\AppupService;
use app\adminapi\controller\Backend;

/**
 * Appup管理-控制器
 * @author 测试
 * @since: 2022/03/19
 * Class Appup
 * @package app\adminapi\controller
 */
class Appup extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/03/19
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AppupService();
    }

                                
}
