<?php namespace app\adminapi\controller;


use app\common\service\ArticleService;
use app\adminapi\controller\Backend;

/**
 * Article管理-控制器
 * @author 测试
 * @since: 2021/09/09
 * Class Article
 * @package app\adminapi\controller
 */
class Article extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/09/09
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ArticleService();
    }

                            
	/**
	 * 设置是否显示
	 * @return mixed
	 * @since 2021/09/09
	 * @author 测试
	 */
	public function setIsShow()
	{
		if (IS_POST) {
			$result = $this->service->setIsShow();
			return $result;
		}
	}
    	            
	/**
	 * 设置是否置顶
	 * @return mixed
	 * @since 2021/09/09
	 * @author 测试
	 */
	public function setIsTop()
	{
		if (IS_POST) {
			$result = $this->service->setIsTop();
			return $result;
		}
	}
    	                	                    
}
