<?php namespace app\adminapi\controller;


use app\common\service\AttachmentService;
use app\adminapi\controller\Backend;

/**
 * Attachment管理-控制器
 * @author 测试
 * @since: 2021/11/26
 * Class Attachment
 * @package app\adminapi\controller
 */
class Attachment extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/11/26
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AttachmentService();
    }

    /**
     * 上传
     * @return mixed
     */
    public function upload()
    {
        $result = $this->service->upload();
        return $result;
    }

    /**
     * 上传文件
     */
    public function upload_file()
    {
        $result = $this->service->uploadFile();
        return $result;
    }
}
