<?php namespace app\adminapi\controller;


use app\common\service\CategoryService;
use app\adminapi\controller\Backend;

/**
 * Category管理-控制器
 * @author 测试
 * @since: 2021/09/18
 * Class Category
 * @package app\adminapi\controller
 */
class Category extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/09/18
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CategoryService();
    }
    /**
     *  添加主营分类
     * @return mixed
     */
    public function add_category()
    {

        $result = $this->service->addCategory();
        return $result;
    }

    /**
     *  查询父级分类
     * @return mixed
     */
    public function sel_parent()
    {

        $result = $this->service->selParent();
        return $result;
    }

    /**
     * 批量导入
     */
    public function export()
    {
        $result = $this->service->export();
        return $result;
    }

}
