<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\CityService;

/**
 * 城市管理-控制器
 * @author 牧羊人
 * @since 2020/11/15
 * Class City
 * @package app\adminapi\controller
 */
class City extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CityService();
    }

    /**
     * 省份和城市列表
     */
    public function city_list()
    {
        $result = $this->service->cityList();
        return $result;
    }

    /**
     * 获取省份列表
     * @return mixed
     */
    public function get_province_list()
    {
        $result = $this->service->getProvinceList();
        return $result;
    }

    /**
     * 获取市列表(通过省份)
     */
    public function get_city_list()
    {
        $result = $this->service->getCityList();
        return $result;
    }
}
