<?php namespace app\adminapi\controller;


use app\common\service\ConsultService;
use app\adminapi\controller\Backend;

/**
 * Consult管理-控制器
 * @author 测试
 * @since: 2022/02/11
 * Class Consult
 * @package app\adminapi\controller
 */
class Consult extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/02/11
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ConsultService();
    }

                    
	/**
	 * 设置是否置顶
	 * @return mixed
	 * @since 2022/02/11
	 * @author 测试
	 */
	public function setIsTop()
	{
		if (IS_POST) {
			$result = $this->service->setIsTop();
			return $result;
		}
	}
    	            	                    
}
