<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\DeptService;
use app\common\service\AdminUserService;

/**
 * 部门管理-控制器
 * @author 牧羊人
 * @since 2020/11/15
 * Class Dept
 * @package app\adminapi\controller
 */
class Dept extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new DeptService();
    }

    /**
     * 获取部门列表
     * @author 牧羊人
     * @since 2021/5/26
     */
    public function getDeptList()
    {
        $result = $this->service->getDeptList();
        return $result;
    }
    /**
     * 获取部门列表
     * @author 牧羊人
     * @since 2021/5/26
     */
    public function getDeptLists()
    {
        $result = $this->service->getDeptLists();
        return $result;
    }

    /**
     * 获取人员下拉列表
     * @author 牧羊人
     * @since 2021/5/26
     */
    public function getPerList()
    {
        $result = $this->service->getPerList($this->user_id);
        return $result;
    }

    /**
     * 获取人员是否为个人权限
     * @author 牧羊人
     * @since 2021/5/26
     */
    public function getPerStatus()
    {
        $result = $this->service->getPerStatus($this->user_id);
        return $result;
    }

    /**
     * 获取部门列表
     * @author 牧羊人
     * @since 2021/5/26
     */
    public function getUserDeptList()
    {
        $result = $this->service->getDeptList();
        return $result;
    }


    /**
     * 部门列表
     */
    public function dept_list()
    {
        $result = $this->service->deptList();
        return $result;
    }

    /**
     * 部门分配
     */
    public function dept_distribution()
    {
        $result = $this->service->deptDistribution($this->user_id);
        return $result;
    }

    /**
     * 查询公司
     */
    public function dept_company()
    {
        $result = $this->service->deptCompany($this->user_id);
        return $result;
    }

    /**
     * 查询 ID 查询层级
     * @return mixed
     */
    public function dept_sel_where_id(){
        $result = $this->service->deptSelWhereId();
        return $result;
    }
    /**
     * 获取收款人员的信息
     */
    public function get_payee(){
        $result = $this->service->getPayee();
        return $result;
    }

    /**
     * 查询结构
     */
    public function dept_structure()
    {
        $result = $this->service->deptStructure($this->user_id);
        return $result;
    }

    /**
     * 公司组别人员
     */
    public function dept_personnel()
    {
        $result = $this->service->deptPersonnel($this->user_id);
        return $result;
    }

    /**
     * 公司组别人员
     */
    public function sel_company()
    {
        $result = $this->service->selCompany($this->user_id);
        return $result;
    }
    /**
     * 编辑修改
     */
    public function edit()
    {
        $result = $this->service->edit();
        return $result;
    }

}
