<?php namespace app\adminapi\controller;


use app\common\service\DocumentService;
use app\adminapi\controller\Backend;

/**
 * Document管理-控制器
 * @author 测试
 * @since: 2022/11/14
 * Class Document
 * @package app\adminapi\controller
 */
class Document extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/14
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new DocumentService();
    }

                    
	/**
	 * 设置是否置顶
	 * @return mixed
	 * @since 2022/11/14
	 * @author 测试
	 */
	public function setIsTop()
	{
		if (IS_POST) {
			$result = $this->service->setIsTop();
			return $result;
		}
	}
    	            	                            
}
