<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\MenuService;
use app\common\service\AdminUserService;
use app\common\service\PlatformMemberService;

/**
 * 系统主页-控制器
 * @author 牧羊人
 * @since 2020/11/14
 * Class Index
 * @package app\adminapi\controller
 */
class Index extends Backend
{

    /**
     * 初始化
     * @return array|void
     * @since 2021/1/8
     * @author 牧羊人
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }
    public function index(){
        echo 1;
        exit;
    }

    /**
     * 获取菜单列表
     * @author 牧羊人
     * @since 2020/11/14
     */
    public function getMenuList()
    {
        $menuService = new MenuService();
        $result = $menuService->getPermissionList($this->user_id);
        return $result;
    }

    /**
     * 获取用户信息
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since 2020/11/20
     * @author 牧羊人
     */
    public function getUserInfo()
    {
        $userService = new AdminUserService();
        $result = $userService->getUserInfo($this->user_id);
        return $result;
    }

    /**
     * 更新个人资料
     * @return mixed
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function updateUserInfo()
    {
        $userService = new AdminUserService();
        $result = $userService->updateUserInfo($this->user_id);
        return $result;
    }

    /**
     * 更新密码
     * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 牧羊人
     * @since 2020/11/15
     */
    public function updatePwd()
    {
        $userService = new AdminUserService();
        $result = $userService->updatePwd($this->user_id);
        return $result;
    }


    public function analysis()
    {
        $platform = new PlatformMemberService();
        $data = $platform->analysis();

        return return_json($data);
    }

}
