<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\LoginService;

/**
 * 登录-控制器
 * @author 牧羊人
 * @since 2020/11/14
 * Class Login
 * @package app\adminapi\controller
 */
class Login extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new LoginService();
    }

    /**
     * 验证码
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function captcha()
    {
        $result = $this->service->captcha();
        return $result;
    }

    /**
     * 登录
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function login()
    {
        $result = $this->service->login();
        return $result;
    }

    /**
     * 退出系统
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function logout()
    {
        $result = $this->service->logout();
        return $result;
    }

}
