<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\MemberService;
use app\common\service\TeamService;
use app\extend\TronTools;

/**
 * 会员管理-控制器
 * @author 牧羊人
 * @since 2020/11/15
 * Class Member
 * @package app\adminapi\controller
 */
class Member extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MemberService();
    }

    public function recharge()
    {
        $result = $this->service->recharge();
        return return_json($result);
    }


    //
    public function team()
    {
        $team = new TeamService();
        $return = $team->adminTeam();
        return return_json($return);
    }

    //
    public function teamtop()
    {
        $team = new TeamService();
        $return = $team->adminTeamTop();
        return return_json($return);
    }

    //查询余额
    public function balance()
    {
        $list = ['balance' => 100];
       // $tron->get_balance()
        $result = $this->service->trx_balance();
        return return_json($result);
    }

    //归集
    public function pooling()
    {
        $result = $this->service->pooling();
        return return_json($result);

    }

    //归集
    public function resetpass()
    {
        $result = $this->service->resetpass();
        return return_json($result);

    }

    //trx
    public function trx()
    {

        $result = $this->service->addTrx();
        return return_json($result);
    }
    //trx
    public function surplus()
    {

        $result = $this->service->surplus();
        return return_json($result);
    }
}
