<?php namespace app\adminapi\controller;


use app\common\service\NewsService;
use app\adminapi\controller\Backend;

/**
 * News管理-控制器
 * @author 测试
 * @since: 2021/12/24
 * Class News
 * @package app\adminapi\controller
 */
class News extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/24
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new NewsService();
    }

    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function add_news()
    {

        $result = $this->service->addNews($this->user_id);
        return $result;
    }
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function admin_user()
    {

        $result = $this->service->adminUser();
        return $result;
    }
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function read_news()
    {

        $result = $this->service->readNews($this->user_id);
        return $result;
    }
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22readAllNews
     */
    public function create_news()
    {

        $result = $this->service->createNews($this->user_id);
        return $result;
    }
    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function read_all_news()
    {

        $result = $this->service->readAllNews($this->user_id);
        return $result;
    }

    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function all_news()
    {

        $result = $this->service->allNews($this->user_id);
        return $result;
    }

    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function check_news()
    {

        $result = $this->service->checkNews($this->user_id);
        return $result;
    }

    /**
     * 初始化方法
     * @author 测试
     * @since: 2021/12/22
     */
    public function all_user()
    {

        $result = $this->service->allUser($this->user_id);
        return $result;
    }

    /**
     * 获取数据列表 我发送的 我收到的
     * @author 测试
     * @since: 2021/12/22
     */
    public function get_user_list()
    {

        $result = $this->service->getUserList($this->user_id,'');
        return $result;
    }
    /**
     * 获取数据列表 我发送的 我收到的
     * @author 测试
     * @since: 2021/12/22
     */
    public function get_user_list1()
    {

        $result = $this->service->getUserList('',$this->user_id);
        return $result;
    }
    /**
     * 获取数据列表 我发送的 我收到的
     * @author 测试
     * @since: 2021/12/22
     */
    public function news_info()
    {

        $result = $this->service->newsInfo();
        return $result;
    }
}
