<?php namespace app\adminapi\controller;


use app\common\service\PlatformMemberService;
use app\adminapi\controller\Backend;

/**
 * Platformmember管理-控制器
 * @author 测试
 * @since: 2022/11/16
 * Class Platformmember
 * @package app\adminapi\controller
 */
class Platformmember extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PlatformMemberService();
    }

                                        
}
