<?php namespace app\adminapi\controller;


use app\common\service\PlatformService;
use app\adminapi\controller\Backend;

/**
 * Platform管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Platform
 * @package app\adminapi\controller
 */
class Platform extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PlatformService();
    }

                    
}
