<?php namespace app\adminapi\controller;


use app\common\service\PolicyService;
use app\adminapi\controller\Backend;

/**
 * Policy管理-控制器
 * @author 测试
 * @since: 2022/11/16
 * Class Policy
 * @package app\adminapi\controller
 */
class Policy extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PolicyService();
    }

                                
}
