<?php namespace app\adminapi\controller;


use app\common\service\QuantPointService;
use app\adminapi\controller\Backend;

/**
 * Quantpoint管理-控制器
 * @author 测试
 * @since: 2022/03/18
 * Class Quantpoint
 * @package app\adminapi\controller
 */
class Quantpoint extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/03/18
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantPointService();
    }

                                        
}
