<?php namespace app\adminapi\controller;


use app\common\service\QuantWalletService;
use app\adminapi\controller\Backend;

/**
 * Quantwallet管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Quantwallet
 * @package app\adminapi\controller
 */
class Quantwallet extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantWalletService();
    }





}
