<?php namespace app\adminapi\controller;


use app\common\service\QuantConfigService;
use app\adminapi\controller\Backend;

/**
 * Quantconfig管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Quantconfig
 * @package app\adminapi\controller
 */
class Quantconfig extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantConfigService();
    }

                            
}
