<?php namespace app\adminapi\controller;


use app\common\service\QuantLogService;
use app\adminapi\controller\Backend;

/**
 * Quantlog管理-控制器
 * @author 测试
 * @since: 2022/02/19
 * Class Quantlog
 * @package app\adminapi\controller
 */
class Quantlog extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/02/19
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantLogService();
    }

                    
}
