<?php namespace app\adminapi\controller;


use app\common\service\QuantTransferService;
use app\adminapi\controller\Backend;

/**
 * Quanttransfer管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Quanttransfer
 * @package app\adminapi\controller
 */
class Quanttransfer extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantTransferService();
    }

    public function list()
    {
        $result = $this->service->list();
        return return_json($result);
    }
}
