<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\RoleService;

/**
 * 角色管理-控制器
 * @author 牧羊人
 * @since 2020/11/14
 * Class Role
 * @package app\adminapi\controller
 */
class Role extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new RoleService();
    }

    /**
     * 获取角色列表
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function getRoleList()
    {
        $result = $this->service->getRoleList();
        return $result;
    }

    /**
     * 获取权限列表
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function getPermissionList()
    {
        $result = $this->service->getPermissionList();
        return $result;
    }

    /**
     * 保存权限
     * @return mixed
     * @since 2020/11/14
     * @author 牧羊人
     */
    public function savePermission()
    {
        $result = $this->service->savePermission();
        return $result;
    }

}
