<?php namespace app\adminapi\controller;


use app\common\service\SingleLoopBuyService;
use app\adminapi\controller\Backend;

/**
 * Singleloopbuy管理-控制器
 * @author 测试
 * @since: 2022/11/16
 * Class Singleloopbuy
 * @package app\adminapi\controller
 */
class Singleloopbuy extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new SingleLoopBuyService();
    }

                                                            
	/**
	 * 设置是否成交
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsDeal()
	{
		if (IS_POST) {
			$result = $this->service->setIsDeal();
			return $result;
		}
	}
    	        
	/**
	 * 设置是否卖出
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsSell()
	{
		if (IS_POST) {
			$result = $this->service->setIsSell();
			return $result;
		}
	}
    	                                                
}
