<?php namespace app\adminapi\controller;


use app\common\service\SingleLoopSellService;
use app\adminapi\controller\Backend;

/**
 * Singleloopsell管理-控制器
 * @author 测试
 * @since: 2022/11/16
 * Class Singleloopsell
 * @package app\adminapi\controller
 */
class Singleloopsell extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new SingleLoopSellService();
    }

                                            
	/**
	 * 设置是否成交
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsDeal()
	{
		if (IS_POST) {
			$result = $this->service->setIsDeal();
			return $result;
		}
	}
    	        
	/**
	 * 设置是否结算
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsBonus()
	{
		if (IS_POST) {
			$result = $this->service->setIsBonus();
			return $result;
		}
	}
    	                                                                
}
