<?php namespace app\adminapi\controller;


use app\common\service\SingleLoopSetupService;
use app\adminapi\controller\Backend;

/**
 * Singleloopsetup管理-控制器
 * @author 测试
 * @since: 2022/11/16
 * Class Singleloopsetup
 * @package app\adminapi\controller
 */
class Singleloopsetup extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/11/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new SingleLoopSetupService();
    }

                            
	/**
	 * 设置是否运行
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsRun()
	{
		if (IS_POST) {
			$result = $this->service->setIsRun();
			return $result;
		}
	}
    	        
	/**
	 * 设置是否循环
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsLoop()
	{
		if (IS_POST) {
			$result = $this->service->setIsLoop();
			return $result;
		}
	}
    	                            
	/**
	 * 设置是否开启补仓
	 * @return mixed
	 * @since 2022/11/16
	 * @author 测试
	 */
	public function setIsOpenDown()
	{
		if (IS_POST) {
			$result = $this->service->setIsOpenDown();
			return $result;
		}
	}
    	                        
}
