<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\adminapi\controller;

use app\common\service\AdminUserService;

/**
 * 用户管理-控制器
 * @author 牧羊人
 * @since 2020/11/14
 * Class User
 * @package app\adminapi\controller
 */
class User extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AdminUserService();
    }

    /**
     * 重置密码
     * @return mixed
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function resetPwd()
    {
        $result = $this->service->resetPwd();
        return $result;
    }

    /**
     * 获取列表
     */
    public function get_admin_user_list()
    {
        $result = $this->service->getAdminUserList();
        return $result;
    }

    /**
     * 用户数据权限添加
     */
    public function add_data_permissions(){
        $result = $this->service->addDataPermissions();
        return $result;
    }

    /**
     * 用户列表
     */
    public function user_list()
    {
        $result = $this->service->userList();
        return $result;
    }

    /**
     * 指派人员列表
     */
    public function assign_user_list()
    {
        $result = $this->service->assignUserList();
        return $result;
    }
}
