<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Appup;

/**
 * app升级管理-服务类
 * @author 测试
 * @since: 2022/03/19
 * Class AppupService
 * @package app\adminapi\service
 */
class AppupService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new Appup();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/03/19
     * @author 测试
     */
    public function getList()
    {


        $param = $this->input;

        // 查询条件
        $map = [];


        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2022/01/23
     * @author 测试
     */
    public function appup()
    {

        $param = $this->input;
        $info = Appup::where('version','>',$param['version'])->where('shebei','=',1)->order('version','DESC')->find();
        if(!$info){
            return ['code'=>1];
        }
        return $info;

    }

    /**
     * 获取数据列表
     * @return array
     * @since 2022/01/23
     * @author 测试
     */
    public function get_appurl()
    {

        $info = Appup::where('shebei','=',1)->order('id','DESC')->find();
        if($info){
            return return_json($info);
        }else{
            return return_json1($info);
        }

    }



}
