<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Article;

/**
 * 文章管理-服务类
 * @author 测试
 * @since: 2021/09/09
 * Class ArticleService
 * @package app\adminapi\service
 */
class ArticleService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new Article();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2021/09/09
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

	
	    // 文章标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }
		
	    // 是否显示
        $is_show = isset($param['is_show']) ? (int)$param['is_show'] : 0;
        if ($is_show) {
            $map[] = ['is_show', '=', $is_show];
        }
		
	    // 是否置顶
        $is_top = isset($param['is_top']) ? (int)$param['is_top'] : 0;
        if ($is_top) {
            $map[] = ['is_top', '=', $is_top];
        }
		
	    // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

	/**
     * 添加或编辑
     * @return array
     * @since 2021/09/09
     * @author 测试
     */
    public function edit()
    {
        // 参数
        $data = $this->input;
	                                
		// 首张图片编号处理
        $cover = trim($data['cover']);
        if (strpos($cover, "temp")) {
            $data['cover'] = save_image($cover, 'article');
        } else {
            $data['cover'] = str_replace(IMG_URL, "", $data['cover']);
        }
                                                                                                                                                                        
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

                        		/**
     * 设置是否显示
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2021/09/09
	 * @author 测试
	 */
    public function setIsShow()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_show']) {
            return message('记录是否显示不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_show' => $data['is_show']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	        		/**
     * 设置是否置顶
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2021/09/09
	 * @author 测试
	 */
    public function setIsTop()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_top']) {
            return message('记录是否置顶不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_top' => $data['is_top']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	            		                    
}
