<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;

use app\common\model\ConfigData;

/**
 * 配置数据-服务类
 * @author 牧羊人
 * @since 2020/11/15
 * Class ConfigService
 * @package app\common\service
 */
class ConfigDataService extends BaseService
{
    /**
     * 构造函数
     * @author 牧羊人
     * @since 2020/11/15
     * ConfigService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new ConfigData();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2021/5/26
     * @author 牧羊人
     */
    public function getList()
    {
        $param = request()->param();
        // 查询条件
        $map = [];
        // 配置ID
        $configId = getter($param, "configId", 0);
        if ($configId) {
            $map[] = ['config_id', '=', $configId];
        }
        // 字典名称
        $name = getter($param, "name");
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
        // 字典编码
        $code = getter($param, 'code');
        if ($code) {
            $map[] = ['code', '=', $code];
        }
        return parent::getList($map, "sort asc"); // TODO: Change the autogenerated stub
    }

}
