<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Document;

/**
 * 文档教程管理-服务类
 * @author 测试
 * @since: 2022/11/14
 * Class DocumentService
 * @package app\adminapi\service
 */
class DocumentService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new Document();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/11/14
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];


	    // 通知标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }

	    // 是否置顶
        $is_top = isset($param['is_top']) ? (int)$param['is_top'] : 0;
        if ($is_top) {
            $map[] = ['is_top', '=', $is_top];
        }

	    // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }

        return parent::getList($map, [], 1, 1); // TODO: Change the autogenerated stub
    }


                		/**
     * 设置是否置顶
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/11/14
	 * @author 测试
	 */
    public function setIsTop()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_top']) {
            return message('记录是否置顶不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_top' => $data['is_top']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }

    public function getInfo()
    {
        // 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
        $list= $this->model->getInfo($data['id']);
        return $list;
    }


}
