<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Member;
use app\common\model\PlatformMember;
use app\common\model\QuantCash;
use app\common\model\QuantTransfer;
use app\common\model\SingleLoopSetup;

/**
 * API配置管理-服务类
 * @author 测试
 * @since: 2022/11/16
 * Class PlatformMemberService
 * @package app\adminapi\service
 */
class PlatformMemberService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new PlatformMember();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/11/16
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

        // 平台名称
        $user_name = isset($param['user_name']) ? trim($param['user_name']) : '';
        if ($user_name) {
            $ids = Member::where('username', 'like', "%{$user_name}%")->column('id');
            $map[] = ['user_id', 'in', $ids];
        }
        // 平台名称
        $platform_id= isset($param['platform_id']) ? trim($param['platform_id']) : '';
        if ($platform_id) {
            $map[] = ['platform_id', '=', $platform_id];
        }
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


    public function getAPI($uset_id){
        $count = $this->model->where('user_id',$uset_id)->count();
        return $count>0?1:2;
    }

//'day_user'=>100,//今日新增用户（
//'day_api_user'=>30,//今日已绑定api用户（数量）
//'user_used'=>150,//用户总数 （已绑定
//'user_unused'=>123,//用户总数 （未绑定
//'day_trans'=>434.21,//今日/ 充值（成功）
//'all_trans'=>453.1,///历史 充值（成功
//'day_cash'=>45.44,//今日/历史 提现（成功）
//'all_cash'=>45.44,//今日/历史 提现（成功）
//'qb_child_all'=>882.11,//今日/历史 直推奖励
//'qb_child_day'=>12.1,//今日/历史 直推奖励
//'qb_team_all'=>123.44,//今日/历史 团队奖励
//'qb_team_day'=>12.11,//今日/历史 团队奖励
//'qb_profit_all'=>777.56,//今日/历史盈利总额
//'qb_profit_day'=>30.2,//今日/历史盈利总额
//'run_setup'=>100,//当前策略开启运行数量
    //数据分析
    public function analysis(){

        //获取当天的时间戳
        $beginToday=mktime(0,0,0,date('m'),date('d'),date('Y'));
        $endToday=mktime(0,0,0,date('m'),date('d')+1,date('Y'))-1;
        //今日新增用户数量
        $day_user = Member::where('mark','1')->where('reg_time','between',[$beginToday,$endToday])->count();

        //所有用户
        $all_user = Member::where('mark','1')->count();
        //今日新增绑定API
        $day_plat = PlatformMember::where('mark','1')->where('create_time','between',[$beginToday,$endToday])->group('user_id')->count();
        //已绑定总人数
        $day_plat_used =PlatformMember::where('mark','1')->group('user_id')->count();
        //未绑定
        $day_plat_unuse =$all_user-$day_plat_used;

        $day_trans= QuantTransfer::where('mark','1')->where('create_time','between',[$beginToday,$endToday])->group('user_id')->sum('value');
        //已绑定总人数
        $all_trans=QuantTransfer::where('mark','1')->sum('value');
        $day_cash= QuantCash::where('mark','1')->where('is_check','1')->where('create_time','between',[$beginToday,$endToday])->group('user_id')->sum('amount');
        //已绑定总人数
        $all_cash=QuantCash::where('mark','1')->where('is_check','1')->sum('amount');

        $qb_child_all = Member::where('mark','1')->sum('qb_child_all');
        //所有用户
        $qb_child_day= Member::where('mark','1')->sum('qb_child_today');

        $qb_team_all= Member::where('mark','1')->sum('qb_team_today');
        //所有用户
        $qb_team_day = Member::where('mark','1')->sum('qb_team_all');

        $qb_profit_all = Member::where('mark','1')->sum('qb_profit_all');
        //所有用户
        $qb_profit_day = Member::where('mark','1')->sum('qb_profit_today');
        $qb_usdt_all = Member::where('mark','1')->sum('qb_usdt');
        $run_setup = SingleLoopSetup::where('mark','1')->where('is_run',1)->count();
        $list =[
            'day_user'=>$day_user,//今日新增用户（
            'day_api_user'=>$day_plat,//今日已绑定api用户（数量）
            'user_used'=>$day_plat_used,//用户总数 （已绑定
            'user_unused'=>$day_plat_unuse,//用户总数 （未绑定
            'day_trans'=>$day_trans,//今日/ 充值（成功）
            'all_trans'=>$all_trans,///历史 充值（成功
            'day_cash'=>$day_cash,//今日/历史 提现（成功）
            'all_cash'=>$all_cash,//今日/历史 提现（成功）
            'qb_child_all'=>$qb_child_all,//今日/历史 直推奖励
            'qb_child_day'=>$qb_child_day,//今日/历史 直推奖励
            'qb_team_all'=>$qb_team_all,//今日/历史 团队奖励
            'qb_team_day'=>$qb_team_day,//今日/历史 团队奖励
            'qb_profit_all'=>$qb_profit_all,//今日/历史盈利总额
            'qb_profit_day'=>$qb_profit_day,//今日/历史盈利总额
            'run_setup'=>$run_setup,//当前策略开启运行数量
            'qb_usdt_all'=>$qb_usdt_all,//当前策略开启运行数量
        ];

    return $list;
    }



}
