<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Policy;

/**
 * 策略分类管理-服务类
 * @author 测试
 * @since: 2022/03/21
 * Class PolicyService
 * @package app\adminapi\service
 */
class PolicyService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new Policy();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/03/21
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

	
	    // 策略名称
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    public function list(){

        $list = $this->model->where('pid','<>',0)->order('id','ASC')->select();
        foreach ($list as &$item) {
//            $item['child']=$this->model->where('pid',$item['id'])->select();
            $item['icon'] = get_images_url($item['icon']);
        }
//        var_dump($list);

        return $list;
    }


                            
}
