<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\ProductMargin;

/**
 * 保证金';管理-服务类
 * @author 测试
 * @since: 2023/09/26
 * Class ProductMarginService
 * @package app\adminapi\service
 */
class ProductMarginService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new ProductMargin();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2023/09/26
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

        $product_id = isset($param['product_id']) ? (int)$param['product_id'] : 0;
        if ($product_id) {
            $map[] = ['product_id', '=', $product_id];
        }
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                            
}
