<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Invate;
use app\common\model\QuantPoint;

/**
 * 点卡流水管理-服务类
 * @author 测试
 * @since: 2022/03/18
 * Class QuantPointService
 * @package app\adminapi\service
 */
class QuantPointService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new QuantPoint();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/03/18
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];
        if(isset($param['start_time']) && isset($param['end_time'])){
            $start = strtotime($param['start_time']);
            $end = strtotime($param['end_time']);
            $map[] = ['create_time', 'BETWEEN', [$start,$end]];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }


    /**
     * 获取该用户的记录
     */
    public function getUserList($user_id,$payment_id='',$type='')
    {
        $map[]=['user_id','=',$user_id];
        //收支类型
        if ($payment_id) {
        $map[] = ['payment_id', '=', $payment_id];
        }else{
            $map[] = ['payment_id', 'IN', '1,2'];
        }
        if ($type) {
            $map[] = ['type_id', '=', $type];
        }else{
            $map[] = ['type_id', 'IN', '1,2,3,4'];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }


    /**
     * 获取该用户的记录
     */
    public function getWorkList($user_id)
    {
        $map = [];
        $param = $this->input;
        if ($param["type_id"] == 1) {
            //查询我的一级邀请
            $user_ids[] = Invate::where(["parent_one_user_id" => $user_id])->column("user_id");
            $map[] = ['user_id', 'in', $user_ids];
        }
        if ($param["type_id"] == 2) {
            //查询我的一级邀请
            $user_ids[] = Invate::where(["parent_two_user_id" => $user_id])->column("user_id");
            $map[] = ['user_id', 'in', $user_ids];
        }




        // 时间检索(日期选择)
        $start_time = isset($param['start_time']) ? $param['start_time'] : "";
        $end_time = isset($param['end_time']) ? $param['end_time'] : "";
        if ($start_time && $end_time) {
            $start_time = strtotime($start_time . " 00:00:00");
            $end_time = strtotime($end_time . " 23:59:59");
            // 筛选条件
            $map[] = ['create_time', '>=', $start_time];
            $map[] = ['create_time', '<=', $end_time];
        }
        return parent::getList($map, "id desc", 1, 1);
    }
}
