<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Member;
use app\common\model\QuantMarketSell;

/**
 * 交易卖出管理-服务类
 * @author 测试
 * @since: 2022/01/23
 * Class QuantMarketSellService
 * @package app\adminapi\service
 */
class QuantMarketSellService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new QuantMarketSell();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/01/23
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

	
	    // 是否成交
        $is_deal = isset($param['is_deal']) ? (int)$param['is_deal'] : 0;
        if ($is_deal) {
            $map[] = ['is_deal', '=', $is_deal];
        }
		
	    // 是否结算
        $is_bonus = isset($param['is_bonus']) ? (int)$param['is_bonus'] : 0;
        if ($is_bonus) {
            $map[] = ['is_bonus', '=', $is_bonus];
        }
        if(isset($param['user_name'])){
//            $ids = Member::where('username','like','%user_name%') ->column('id');
            $ids = Member::where('username','like',"%{$param['user_name']}%") ->column('id');
//            var_dump($ids);die;
            $map[]=['user_id','IN',$ids];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                                    		/**
     * 设置是否成交
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/01/23
	 * @author 测试
	 */
    public function setIsDeal()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_deal']) {
            return message('记录是否成交不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_deal' => $data['is_deal']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	    		/**
     * 设置是否结算
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/01/23
	 * @author 测试
	 */
    public function setIsBonus()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_bonus']) {
            return message('记录是否结算不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_bonus' => $data['is_bonus']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }


    //一键补单
    public function sell($userId)
    {
        $validate = getValidate([
            'setup_id' => 'require',
        ], [
            'setup_id.require' => '请选择交易品种',
        ]);
        if ($validate['code'] == 1) {
            return $validate;
        }
        $map =[];
        $map[]=['setup_id','=',$this->input['setup_id']];

        return parent::getList($map); // TODO: Change the autogenerated stub

    }
    	                
}
