<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\QuantDay;

/**
 * 汇总记录管理-服务类
 * @author 测试
 * @since: 2022/01/23
 * Class QuantDayService
 * @package app\adminapi\service
 */
class QuantDayService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new QuantDay();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/01/23
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

	
	    // 是否汇总
        $is_deal = isset($param['is_deal']) ? (int)$param['is_deal'] : 0;
        if ($is_deal) {
            $map[] = ['is_deal', '=', $is_deal];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


            		/**
     * 设置是否汇总
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/01/23
	 * @author 测试
	 */
    public function setIsDeal()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_deal']) {
            return message('记录是否汇总不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_deal' => $data['is_deal']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	            
}
