<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\QuantLog;

/**
 * 操作记录管理-服务类
 * @author 测试
 * @since: 2022/02/19
 * Class QuantLogService
 * @package app\adminapi\service
 */
class QuantLogService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new QuantLog();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/02/19
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];


        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                    
}
