<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\QuantConfig;

/**
 * 后台配置管理-服务类
 * @author 测试
 * @since: 2022/01/23
 * Class QuantConfigService
 * @package app\adminapi\service
 */
class QuantConfigService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new QuantConfig();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2022/01/23
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];


        //
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }

        //
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }



    public function get_cash_config()
    {
        $result=get_config('cash_fee,min_fee,move_fee');
        return $result;
    }

    public function get_point_config()
    {
        $result=get_config('point,platform_fee,min_point_fee,use_min_fee');
        return $result;
    }
    public function get_kefu_config()
    {
        $result=get_config('qq,qq_qun,customer');

        if(isset($result['qq_qun'])){
            $result['qq_qun'] = explode(",",$result['qq_qun']);
//            $result['qq_qun'] = array_chunk($result['qq_qun'],2);//把数组以多少位分成一个数组合并为二维数组
        }
//        if(isset($result['wechat'])){
//            $result['wechat'] = get_images_url($result['wechat']);
//
//        }
        return $result;
    }
    /**
     * 添加或编辑
     * @return array
     * @since 2020/11/21
     * @author 牧羊人
     */
    public function edit()
    {
        // 请求参数
        $data = request()->param();
        //文件处理


        $avatar = getter($data, 'type');

        if($avatar ==5 ||$avatar ==4){

            $data['value'] = str_replace(IMG_URL, "", $data['value']);

        }

        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}
