<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Member;
use app\common\model\SingleLoopSell;

/**
 * 交易卖出管理-服务类
 * @author 测试
 * @since: 2022/11/16
 * Class SingleLoopSellService
 * @package app\adminapi\service
 */
class SingleLoopSellService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new SingleLoopSell();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/11/16
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];

        if(isset($param['start_time']) && isset($param['end_time'])){
            $start = strtotime($param['start_time']);
            $end = strtotime($param['end_time']);
            $map[] = ['create_time', 'BETWEEN', [$start,$end]];
        }
        // 平台名称
        $symbol = isset($param['symbol']) ? trim($param['symbol']) : '';
        if ($symbol) {
            $symbol = strtoupper($symbol);
            $map[] = ['symbol', 'like', "%{$symbol}%"];
        }
        // 平台名称
        $order_id= isset($param['order_id']) ? trim($param['order_id']) : '';
        if ($order_id) {
            $map[] = ['order_id', 'like', "%{$order_id}%"];
        }
        // 平台名称
        $user_name = isset($param['user_name']) ? trim($param['user_name']) : '';
        if ($user_name) {
            $ids = Member::where('username', 'like', "%{$user_name}%")->column('id');
            $map[] = ['user_id', 'in', $ids];
        }
        // 是否成交
        $is_deal = isset($param['is_deal']) ? (int)$param['is_deal'] : 0;
        if ($is_deal) {
            $map[] = ['is_deal', '=', $is_deal];
        }
        // 是否成交
        $platform_id = isset($param['platform_id']) ? (int)$param['platform_id'] : 0;
        if ($platform_id) {
            $map[] = ['platform_id', '=', $platform_id];
        }


	    // 是否结算
        $is_bonus = isset($param['is_bonus']) ? (int)$param['is_bonus'] : 0;
        if ($is_bonus) {
            $map[] = ['is_bonus', '=', $is_bonus];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                                        		/**
     * 设置是否成交
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/11/16
	 * @author 测试
	 */
    public function setIsDeal()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_deal']) {
            return message('记录是否成交不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_deal' => $data['is_deal']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	    		/**
     * 设置是否结算
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/11/16
	 * @author 测试
	 */
    public function setIsBonus()
    {
		// 参数
        $data = $this->input;
        if (!$data['id']) {
            return message('记录ID不能为空', false);
        }
		if (!$data['is_bonus']) {
            return message('记录是否结算不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $data['id'],
            'is_bonus' => $data['is_bonus']
        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }

}
