<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\SingleLeverConfig;

/**
 * 交易策略管理-服务类
 * @author 测试
 * @since: 2022/11/16
 * Class SingleLeverConfigService
 * @package app\adminapi\service
 */
class SingleLeverConfigService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new SingleLeverConfig();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/11/16
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];
        if(isset($param['start_time']) && isset($param['end_time'])){
            $start = strtotime($param['start_time']);
            $end = strtotime($param['end_time']);
            $map[] = ['create_time', 'BETWEEN', [$start,$end]];
        }
        // 平台名称
        $lever= isset($param['lever']) ? trim($param['lever']) : '';
        if ($lever) {
            $map[] = ['lever', '=', $lever];
        }
        // 平台名称
        $rounds= isset($param['rounds']) ? trim($param['rounds']) : '';
        if ($rounds) {
            $map[] = ['rounds', '=', $rounds];
        }

        $type_id= isset($param['type_id']) ? trim($param['type_id']) : '';
        if ($type_id) {
            $map[] = ['type_id', '=', $type_id];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }



}
