<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\Member;
use app\common\model\TradeLog;

/**
 * 交易日志管理-服务类
 * @author 测试
 * @since: 2022/11/15
 * Class TradeLogService
 * @package app\adminapi\service
 */
class TradeLogService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new TradeLog();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/11/15
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];


        // 平台名称
        $content= isset($param['content']) ? trim($param['content']) : '';
        if ($content) {
            $map[] = ['content', 'like', "%{$content}%"];
        }
        $symbol= isset($param['symbol']) ? trim($param['symbol']) : '';
        if ($symbol) {
            $symbol = strtoupper($symbol);
            $map[] = ['symbol', 'like', "%{$symbol}%"];
        }

        // 平台名称
        $user_name = isset($param['user_name']) ? trim($param['user_name']) : '';
        if ($user_name) {
            $ids = Member::where('username', 'like', "%{$user_name}%")->column('id');
            $map[] = ['user_id', 'in', $ids];
        }
        // 是否成交
        $platform_id= isset($param['platform_id']) ? (int)$param['platform_id'] : 0;
        if ($platform_id) {
            $map[] = ['platform_id', '=', $platform_id];
        }

        // 是否成交
        $open_type = isset($param['open_type']) ? (int)$param['open_type'] : 0;
        if ($open_type) {
            $map[] = ['open_type', '=', $open_type];
        }

        // 是否成交
        $type= isset($param['type']) ? (int)$param['type'] : 0;
        if ($type) {
            $map[] = ['type', '=', $type];
        }


        return parent::getList($map, [], 0, 1); // TODO: Change the autogenerated stub
    }



}
