<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\service;


use app\common\model\UsdtLog;

/**
 * 归集USDT管理-服务类
 * @author 测试
 * @since: 2022/12/10
 * Class UsdtLogService
 * @package app\adminapi\service
 */
class UsdtLogService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->model = new UsdtLog();
    }

	/**
     * 获取数据列表
     * @return array
     * @since 2022/12/10
     * @author 测试
     */
    public function getList()
    {
        $param = $this->input;

        // 查询条件
        $map = [];
        $user_id= isset($param['user_id']) ? (int)$param['user_id'] : 0;
        if ($user_id) {
            $map[] = ['user_id', '=', $user_id];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }



}
