<?php namespace app\v2\controller;


use app\common\service\QuantMarketBuyService;
use app\common\service\TradeProfitService;
use app\v1\controller\Backend;

/**
 * Quantmarketbuy前端管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Quantmarketbuy
 * @package app\v1\controller
 */
class Buy extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new QuantMarketBuyService();
    }


    /**
     * @return \think\response\Json
     * 获取AI配置项
     */
    public function  ranking()
    {
        $this->q= new TradeProfitService();
//        return return_json($this->q->get_user_profit($this->user_id));
        return return_json($this->q->ranking());
    }

}
