<?php

namespace app\v2\controller;


use app\common\service\PlatformService;
use app\v1\controller\Backend;

/**
 * Platform前端管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Platform
 * @package app\v1\controller
 */
class Platform extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PlatformService();
    }


    /**
     * 获取数据列表
     * @return mixed
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function platform()
    {
        $result = $this->service->plantform($this->user_id);
        return return_json($result);
    }
    /**
     * 获取数据列表
     * @return mixed
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function edit()
    {
        $result = $this->service->edit($this->user_id);
        return $result;
    }

}
