<?php namespace app\v2\controller;


use app\common\model\Appup;
use app\common\service\SymbolService;
use app\v2\controller\Backend;

/**
 * Quantsymbol前端管理-控制器
 * @author 测试
 * @since: 2022/01/23
 * Class Quantsymbol
 * @package app\v1\controller
 */
class Symbol extends Backend
{
    /**
     * 初始化方法
     * @author 测试
     * @since: 2022/01/23
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new SymbolService();
    }

    /**
     * 首页随机展示10条代币类型
     */
    public function round(){
          $data =  $this->service->round();
        return return_json($data);
    }


    /**
     *下载链接android
     */
    public function download(){
        $info = Appup::where('shebei','=',1)->order('version','DESC')->value('url');

        $data = ['android'=>$info,'ios'=>IOS_URL,'h5'=>H5_URL];
        return return_json($data);
    }


}
